repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy apps turkdemy
        language: system
        pass_filenames: false
        require_serial: true


  - repo: local
    hooks:
      - id: django-check
        name: django system check
        entry: uv run python manage.py check
        language: system
        pass_filenames: false
