# Generated by Django 5.2.17 on 2026-09-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='event_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='event_type',
            field=models.CharField(blank=True, choices=[('program_recommended', 'Program recommended'), ('document_replacement_uploaded', 'Document replacement uploaded'), ('document_replacement_requested', 'Document replacement requested'), ('lead_finalized', 'Applicant finalized')], max_length=64),
        ),
    ]
