# Generated by Django 5.2.17 on 2026-08-24 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geography", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name_en", models.CharField(max_length=50)),
                ("name_fa", models.CharField(blank=True, max_length=50)),
                ("name_tr", models.CharField(blank=True, max_length=50)),
                ("name_ar", models.CharField(blank=True, max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_fa", models.CharField(blank=True, max_length=255)),
                ("name_tr", models.CharField(blank=True, max_length=255)),
                ("name_ar", models.CharField(blank=True, max_length=255)),
                ("slug_en", models.SlugField(max_length=255)),
                ("slug_fa", models.SlugField(blank=True, max_length=255)),
                ("slug_tr", models.SlugField(blank=True, max_length=255)),
                ("slug_ar", models.SlugField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_fa", models.TextField(blank=True)),
                ("description_tr", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramLanguage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_fa", models.CharField(blank=True, max_length=255)),
                ("name_tr", models.CharField(blank=True, max_length=255)),
                ("name_ar", models.CharField(blank=True, max_length=255)),
                ("slug_en", models.SlugField(max_length=255)),
                ("slug_fa", models.SlugField(blank=True, max_length=255)),
                ("slug_tr", models.SlugField(blank=True, max_length=255)),
                ("slug_ar", models.SlugField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_fa", models.TextField(blank=True)),
                ("description_tr", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_fa", models.CharField(blank=True, max_length=255)),
                ("name_tr", models.CharField(blank=True, max_length=255)),
                ("name_ar", models.CharField(blank=True, max_length=255)),
                ("slug_en", models.SlugField(max_length=255)),
                ("slug_fa", models.SlugField(blank=True, max_length=255)),
                ("slug_tr", models.SlugField(blank=True, max_length=255)),
                ("slug_ar", models.SlugField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_fa", models.TextField(blank=True)),
                ("description_tr", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("associate", "Associate"),
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("phd", "PhD"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "thesis_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("thesis", "With Thesis"),
                            ("non_thesis", "Without Thesis"),
                        ],
                        help_text="Indicates whether a graduate program is thesis or non-thesis, when applicable.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("duration", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "listing_priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Internal priority used to influence this item's position in listings. Higher values receive greater priority.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="universities.department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="universities.programlanguage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name_en", models.CharField(max_length=100)),
                ("name_fa", models.CharField(blank=True, max_length=100)),
                ("name_tr", models.CharField(blank=True, max_length=100)),
                ("name_ar", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramOffering",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "fee_basis",
                    models.CharField(
                        choices=[
                            ("annual", "Annual"),
                            ("whole_program", "Total (Whole Program)"),
                        ],
                        help_text="Specifies what period or unit the tuition amount applies to, such as per year or for the full program.",
                        max_length=30,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("TRY", "Turkish Lira"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "tuition",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Standard tuition amount before discounts for this program offering.",
                        max_digits=12,
                    ),
                ),
                (
                    "tuition_discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tuition_discounted",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cash_discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "tuition_cash",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "tuition_annual_installment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "pre_school_fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "quota",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of admission places available for this offering, when known.",
                        null=True,
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True,
                        help_text="Last date on which an application can be submitted for this offering.",
                        null=True,
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_offerings",
                        to="universities.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="universities.program",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="program_offerings",
                        to="universities.semester",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_en", models.CharField(max_length=255)),
                ("name_fa", models.CharField(blank=True, max_length=255)),
                ("name_tr", models.CharField(blank=True, max_length=255)),
                ("name_ar", models.CharField(blank=True, max_length=255)),
                ("slug_en", models.SlugField(max_length=255)),
                ("slug_fa", models.SlugField(blank=True, max_length=255)),
                ("slug_tr", models.SlugField(blank=True, max_length=255)),
                ("slug_ar", models.SlugField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_fa", models.TextField(blank=True)),
                ("description_tr", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, upload_to="universities/logos/"),
                ),
                (
                    "banner",
                    models.ImageField(blank=True, upload_to="universities/banners/"),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "university_type",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        max_length=20,
                    ),
                ),
                (
                    "is_yok_recognized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the university is recognized by YÖK (the Council of Higher Education of Türkiye).",
                    ),
                ),
                (
                    "is_moe_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the university is approved by the relevant Ministry of Education for the target student market.",
                    ),
                ),
                (
                    "is_moh_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the university is approved by the relevant Ministry of Health for the target student market.",
                    ),
                ),
                (
                    "has_erasmus",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the university participates in the Erasmus+ mobility programme.",
                    ),
                ),
                (
                    "has_dormitory",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the university provides or officially offers student dormitory accommodation.",
                    ),
                ),
                (
                    "ranking_qs",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="University ranking position according to QS World University Rankings.",
                        null=True,
                    ),
                ),
                (
                    "ranking_the",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="University ranking position according to Times Higher Education (THE).",
                        null=True,
                    ),
                ),
                (
                    "ranking_arwu",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="University ranking position according to ARWU.",
                        null=True,
                    ),
                ),
                (
                    "ranking_urap",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="University ranking position according to URAP.",
                        null=True,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "listing_priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Internal priority used to influence this item's position in listings. Higher values receive greater priority.",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="universities",
                        to="geography.city",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="program",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="universities.university",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="universities.university",
            ),
        ),
        migrations.CreateModel(
            name="UniversityMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="universities/media/")),
                ("title", models.CharField(blank=True, max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="universities.university",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
