# Generated by Django 5.2.17 on 2026-08-29 21:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programoffering',
            name='pre_school_fees',
        ),
        migrations.AddField(
            model_name='program',
            name='duration_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='study_mode',
            field=models.CharField(choices=[('on_campus', 'On campus'), ('distance', 'Distance learning'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='on_campus', max_length=20),
        ),
        migrations.AddField(
            model_name='programoffering',
            name='notes',
            field=models.TextField(blank=True, help_text='Preserve source footnotes, exceptional charges, or ambiguous terms here.'),
        ),
        migrations.AddField(
            model_name='programoffering',
            name='preparation_included',
            field=models.BooleanField(default=False, help_text='Whether the quoted tuition includes preparatory study.'),
        ),
        migrations.AddField(
            model_name='programoffering',
            name='preparatory_tuition',
            field=models.DecimalField(blank=True, db_column='pre_school_fees', decimal_places=2, help_text='Tuition for language/foundation preparatory study.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='programoffering',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programoffering',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Deprecated duration in whole years.', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_language',
            field=models.ForeignKey(blank=True, help_text='Deprecated single-language compatibility field.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_programs', to='universities.programlanguage'),
        ),
        migrations.CreateModel(
            name='AcademicUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_fa', models.CharField(blank=True, max_length=255)),
                ('name_tr', models.CharField(blank=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('slug_en', models.SlugField(max_length=255)),
                ('slug_fa', models.SlugField(blank=True, max_length=255)),
                ('slug_tr', models.SlugField(blank=True, max_length=255)),
                ('slug_ar', models.SlugField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('unit_type', models.CharField(choices=[('faculty', 'Faculty'), ('school', 'School'), ('institute', 'Institute'), ('vocational_school', 'Vocational School'), ('conservatory', 'Conservatory'), ('college', 'College'), ('graduate_school', 'Graduate School'), ('other', 'Other')], max_length=30)),
                ('description_en', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True)),
                ('description_tr', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_units', to='universities.university')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='program',
            name='academic_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='universities.academicunit'),
        ),
        migrations.CreateModel(
            name='ProgramInstructionLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('is_primary', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_language_rows', to='universities.programlanguage')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_language_rows', to='universities.program')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='instruction_languages',
            field=models.ManyToManyField(blank=True, related_name='programs', through='universities.ProgramInstructionLanguage', to='universities.programlanguage'),
        ),
        migrations.CreateModel(
            name='UniversityCatalogueSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='universities/catalogue-sources/')),
                ('received_at', models.DateField()),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_sources', to='universities.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_catalogue_sources', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_sources', to='universities.university')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='programoffering',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='universities.universitycataloguesource'),
        ),
        migrations.AddConstraint(
            model_name='programinstructionlanguage',
            constraint=models.UniqueConstraint(fields=('program', 'language'), name='uniq_program_instruction_language'),
        ),
    ]
