# Generated by Django 5.2.17 on 2026-08-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_remove_programoffering_pre_school_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal staff/import notes. Never expose this field on public or customer-facing surfaces.'),
        ),
    ]
