# Generated by Django 5.2.17 on 2026-08-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_program_internal_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicunit',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='academicunit',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='academicunit',
            name='slug_tr',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug_tr',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug_tr',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='programlanguage',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='programlanguage',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='programlanguage',
            name='slug_tr',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug_tr',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
    ]
