# Generated by Django 5.2.17 on 2026-08-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_alter_academicunit_slug_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicunit',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='programlanguage',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
