# Generated by Django 5.2.17 on 2026-08-30 10:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0005_alter_academicunit_slug_en_alter_department_slug_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='programoffering',
            name='fee_basis',
            field=models.CharField(choices=[('annual', 'Annual'), ('semester', 'Per semester'), ('whole_program', 'Total (Whole Program)'), ('per_credit', 'Per credit'), ('one_time', 'One time')], help_text='Specifies what period or unit the tuition amount applies to, such as per year or for the full program.', max_length=30),
        ),
        migrations.AlterField(
            model_name='programoffering',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_offerings', to='universities.semester'),
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_fa', models.CharField(blank=True, max_length=100)),
                ('name_tr', models.CharField(blank=True, max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('application_open', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intakes', to='universities.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='universities.university')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='programoffering',
            name='intake',
            field=models.ForeignKey(blank=True, help_text='Canonical intake. Fall/Spring/Academic Intake are intake names.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_offerings', to='universities.intake'),
        ),
        migrations.CreateModel(
            name='OfferingFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition / list fee'), ('discounted_tuition', 'Discounted tuition'), ('advance_payment', 'Advance payment'), ('cash_payment', 'Cash payment'), ('installment_total', 'Installment total'), ('deposit', 'Deposit'), ('preparatory', 'Preparatory / foundation tuition'), ('application', 'Application fee'), ('registration', 'Registration fee'), ('other', 'Other')], max_length=30)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('TRY', 'Turkish Lira')], max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('basis', models.CharField(choices=[('annual', 'Annual'), ('semester', 'Per semester'), ('whole_program', 'Total (Whole Program)'), ('per_credit', 'Per credit'), ('one_time', 'One time')], default='annual', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offering_fees', to='universities.programlanguage')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='universities.programoffering')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
