# Generated by Django 5.2.17 on 2026-08-31 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_alter_programoffering_fee_basis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programoffering',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='program',
            name='program_language',
        ),
        migrations.RemoveField(
            model_name='programoffering',
            name='cash_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='programoffering',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='programoffering',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='programoffering',
            name='fee_basis',
        ),
        migrations.RemoveField(
            model_name='programoffering',
            name='preparatory_tuition',
        ),
        migrations.RemoveField(
            model_name='programoffering',
            name='tuition',
        ),
        migrations.RemoveField(
            model_name='programoffering',
            name='tuition_annual_installment',
        ),
        migrations.RemoveField(
            model_name='programoffering',
            name='tuition_cash',
        ),
        migrations.RemoveField(
            model_name='programoffering',
            name='tuition_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='programoffering',
            name='tuition_discounted',
        ),
        migrations.AlterField(
            model_name='programoffering',
            name='intake',
            field=models.ForeignKey(help_text='Canonical intake. Fall/Spring/Academic Intake are intake names.', on_delete=django.db.models.deletion.PROTECT, related_name='program_offerings', to='universities.intake'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
