# Generated by Django 5.2.17 on 2026-08-31 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_remove_programoffering_semester_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_en', ''), _negated=True), fields=('slug_en',), name='uniq_program_slug_en'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_fa', ''), _negated=True), fields=('slug_fa',), name='uniq_program_slug_fa'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_tr', ''), _negated=True), fields=('slug_tr',), name='uniq_program_slug_tr'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_ar', ''), _negated=True), fields=('slug_ar',), name='uniq_program_slug_ar'),
        ),
    ]
