# Generated by Django 5.2.17 on 2026-09-03 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0008_program_uniq_program_slug_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_fa', models.CharField(blank=True, max_length=255)),
                ('name_tr', models.CharField(blank=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('slug_en', models.SlugField(blank=True, max_length=255)),
                ('slug_fa', models.SlugField(allow_unicode=True, blank=True, max_length=255)),
                ('slug_tr', models.SlugField(allow_unicode=True, blank=True, max_length=255)),
                ('slug_ar', models.SlugField(allow_unicode=True, blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_fa', models.TextField(blank=True)),
                ('description_tr', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=255)),
                ('seo_title_fa', models.CharField(blank=True, max_length=255)),
                ('seo_title_tr', models.CharField(blank=True, max_length=255)),
                ('seo_title_ar', models.CharField(blank=True, max_length=255)),
                ('seo_description_en', models.TextField(blank=True)),
                ('seo_description_fa', models.TextField(blank=True)),
                ('seo_description_tr', models.TextField(blank=True)),
                ('seo_description_ar', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'name_en'),
            },
        ),
        migrations.AddField(
            model_name='program',
            name='general_field',
            field=models.ForeignKey(blank=True, help_text='TurkDemy-curated general study field. Assign manually after catalogue import and verification; importers must not populate or overwrite it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='universities.generalfield'),
        ),
        migrations.AddConstraint(
            model_name='generalfield',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_en', ''), _negated=True), fields=('slug_en',), name='uniq_general_field_slug_en'),
        ),
        migrations.AddConstraint(
            model_name='generalfield',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_fa', ''), _negated=True), fields=('slug_fa',), name='uniq_general_field_slug_fa'),
        ),
        migrations.AddConstraint(
            model_name='generalfield',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_tr', ''), _negated=True), fields=('slug_tr',), name='uniq_general_field_slug_tr'),
        ),
        migrations.AddConstraint(
            model_name='generalfield',
            constraint=models.UniqueConstraint(condition=models.Q(('slug_ar', ''), _negated=True), fields=('slug_ar',), name='uniq_general_field_slug_ar'),
        ),
    ]
