# Generated by Django 5.2.17 on 2026-09-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0009_generalfield_program_general_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='general_field',
        ),
        migrations.AddField(
            model_name='program',
            name='general_fields',
            field=models.ManyToManyField(blank=True, help_text='TurkDemy-curated general study fields. Assign manually after catalogue import and verification; importers must not populate, overwrite, or clear them.', related_name='programs', to='universities.generalfield'),
        ),
    ]
