# Generated by Django 5.2.17 on 2026-08-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='key',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
