# Generated by Django 5.2.17 on 2026-08-27 14:18

import apps.core.validators
import apps.students.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cell', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_phone_number])),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('english_test_type', models.CharField(blank=True, choices=[('toefl', 'TOEFL'), ('ielts', 'IELTS'), ('pte', 'PTE'), ('cambridge', 'Cambridge'), ('other', 'Other')], max_length=20)),
                ('english_language_test_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('high_school_gpa', models.DecimalField(blank=True, decimal_places=2, help_text="Student's final high-school grade or GPA in the original grading system, for example 17.5 on a 20-point scale or 3.5 on a 4-point scale.", max_digits=5, null=True)),
                ('high_school_gpa_scale', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum value of the grading scale used for the high-school grade or GPA, for example 20, 4, 10, or 100.', max_digits=5, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('passport_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('passport_issuing_authority', models.CharField(blank=True, max_length=255)),
                ('passport', models.FileField(blank=True, upload_to='students/passports/')),
                ('passport_date_of_issue', models.DateField(blank=True, null=True)),
                ('passport_date_of_expiry', models.DateField(blank=True, null=True)),
                ('city_of_residence', models.CharField(blank=True, help_text='City of residence as free text.', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('educational_background', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='agents.agent')),
                ('country_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_born', to='geography.country')),
                ('country_of_residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_residing', to='geography.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students_nationality', to='geography.country')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated account that owns/manages this student record. One account may manage multiple students.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('passport_copy', 'Passport Copy'), ('passport_photo', 'Passport Size Photo'), ('id_card', 'ID Card'), ('diploma', 'Diploma'), ('transcript', 'Transcript'), ('turkish_proficiency', 'Turkish Proficiency Certificate'), ('language_certificate', 'Language Certificate'), ('yok_recognition', 'YÖK Recognition Certificate'), ('yok_equivalency', 'YÖK Equivalency Certificate'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to=apps.students.models.student_document_upload_path)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
