# Generated by Django 5.2.17 on 2026-08-27 14:18

import apps.leads.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('geography', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDocumentReviewHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_status', models.CharField(choices=[('pending', 'Needs review'), ('approved', 'Approved'), ('replacement_requested', 'Replacement requested')], max_length=32)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-reviewed_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LeadDocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=500, upload_to=apps.leads.models.lead_document_version_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('review_status', models.CharField(choices=[('pending', 'Needs review'), ('approved', 'Approved'), ('replacement_requested', 'Replacement requested')], max_length=32)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeadPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tuition_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tuition_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tuition_currency', models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('TRY', 'Turkish Lira')], max_length=3)),
                ('preferred_degrees', models.JSONField(blank=True, default=list, help_text='Degree codes such as bachelor, master or phd.')),
                ('preferred_university_types', models.JSONField(blank=True, default=list, help_text='University type codes such as public or private.')),
                ('requires_dormitory', models.BooleanField(blank=True, null=True)),
                ('requires_erasmus', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional study preferences or constraints.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeadProgramInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('user', 'User-added'), ('agent', 'Agent-suggested')], default='user', max_length=16)),
                ('suggestion_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('finalized', 'Finalized'), ('closed', 'Closed')], db_index=True, default='new', max_length=32)),
                ('source', models.CharField(choices=[('website', 'Website'), ('agent', 'Agent'), ('staff', 'Staff'), ('system', 'System'), ('other', 'Other')], default='website', max_length=24)),
                ('needs_program_recommendation', models.BooleanField(db_index=True, default=False, help_text='The applicant is unsure which programs are suitable and wants TurkDemy staff/system to investigate and suggest options.')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cell', models.CharField(blank=True, max_length=40)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('english_test_type', models.CharField(blank=True, choices=[('toefl', 'TOEFL'), ('ielts', 'IELTS'), ('pte', 'PTE'), ('cambridge', 'Cambridge'), ('other', 'Other')], max_length=20)),
                ('english_language_test_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('high_school_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('high_school_gpa_scale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('passport_no', models.CharField(blank=True, db_index=True, max_length=100)),
                ('passport_issuing_authority', models.CharField(blank=True, max_length=255)),
                ('passport_date_of_issue', models.DateField(blank=True, null=True)),
                ('passport_date_of_expiry', models.DateField(blank=True, null=True)),
                ('city_of_residence', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('educational_background', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes.')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='agents.agent')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Internal staff user currently responsible for this lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('converted_student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='students.student')),
                ('country_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads_born', to='geography.country')),
                ('country_of_residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads_residing', to='geography.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads_nationality', to='geography.country')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Authenticated account that owns and manages this applicant.', on_delete=django.db.models.deletion.PROTECT, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('note', 'Note'), ('applicant_updated', 'Applicant data updated'), ('internal_notes_updated', 'Internal notes updated'), ('status_changed', 'Status changed'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('validated', 'Validated'), ('document_uploaded', 'Document uploaded'), ('document_reviewed', 'Document reviewed'), ('program_added', 'Program added'), ('program_suggested', 'Program suggested'), ('program_response', 'Program response'), ('recommendations_generated', 'Recommendations generated'), ('finalized', 'Finalized')], max_length=40)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_customer_visible', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('passport_copy', 'Passport Copy'), ('passport_photo', 'Passport Size Photo'), ('id_card', 'ID Card'), ('diploma', 'Diploma'), ('transcript', 'Transcript'), ('turkish_proficiency', 'Turkish Proficiency Certificate'), ('language_certificate', 'Language Certificate'), ('yok_recognition', 'YÖK Recognition Certificate'), ('yok_equivalency', 'YÖK Equivalency Certificate'), ('other', 'Other')], max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=apps.leads.models.lead_document_upload_path)),
                ('description', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Needs review'), ('approved', 'Approved'), ('replacement_requested', 'Replacement requested')], db_index=True, default='pending', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('converted_student_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead_document', to='students.studentdocument')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.lead')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
