# Generated by Django 5.2.17 on 2026-08-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
