# Generated by Django 5.2.17 on 2026-08-27 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('geography', '0001_initial'),
        ('leads', '0001_initial'),
        ('messaging', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddocument',
            name='source_message_attachment',
            field=models.OneToOneField(blank=True, help_text='Chat attachment this document was promoted from, when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_document', to='messaging.messageattachment'),
        ),
        migrations.AddField(
            model_name='leaddocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaddocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaddocumentreviewhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaddocumentreviewhistory',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to='leads.leaddocument'),
        ),
        migrations.AddField(
            model_name='leaddocumentreviewhistory',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaddocumentreviewhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaddocumentversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaddocumentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='leads.leaddocument'),
        ),
        migrations.AddField(
            model_name='leaddocumentversion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaddocumentversion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadpreference',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadpreference',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadpreference',
            name='preferred_cities',
            field=models.ManyToManyField(blank=True, related_name='lead_preferences', to='geography.city'),
        ),
        migrations.AddField(
            model_name='leadpreference',
            name='preferred_departments',
            field=models.ManyToManyField(blank=True, related_name='lead_preferences', to='universities.department'),
        ),
        migrations.AddField(
            model_name='leadpreference',
            name='preferred_languages',
            field=models.ManyToManyField(blank=True, related_name='lead_preferences', to='universities.programlanguage'),
        ),
        migrations.AddField(
            model_name='leadpreference',
            name='preferred_universities',
            field=models.ManyToManyField(blank=True, related_name='lead_preferences', to='universities.university'),
        ),
        migrations.AddField(
            model_name='leadpreference',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadprograminterest',
            name='converted_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead_interest', to='applications.application'),
        ),
        migrations.AddField(
            model_name='leadprograminterest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadprograminterest',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_interests', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadprograminterest',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_interests', to='universities.program'),
        ),
        migrations.AddField(
            model_name='leadprograminterest',
            name='program_offering',
            field=models.ForeignKey(blank=True, help_text='Specific intake/offering when known. Program-level interest is allowed without selecting an offering.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_interests', to='universities.programoffering'),
        ),
        migrations.AddField(
            model_name='leadprograminterest',
            name='suggested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadprograminterest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', 'status'], name='leads_lead_user_id_8f1913_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='leads_lead_assigne_92225c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['needs_program_recommendation', 'status'], name='leads_lead_needs_p_34b023_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadprograminterest',
            constraint=models.UniqueConstraint(condition=models.Q(('program_offering__isnull', True)), fields=('lead', 'program'), name='unique_lead_program_without_offering'),
        ),
        migrations.AddConstraint(
            model_name='leadprograminterest',
            constraint=models.UniqueConstraint(condition=models.Q(('program_offering__isnull', False)), fields=('lead', 'program', 'program_offering'), name='unique_lead_program_offering_interest'),
        ),
    ]
