# Generated by Django 5.2.17 on 2026-08-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadactivity_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Created'), ('note', 'Note'), ('applicant_updated', 'Applicant data updated'), ('internal_notes_updated', 'Internal notes updated'), ('status_changed', 'Status changed'), ('assigned', 'Assigned'), ('reassigned', 'Reassigned'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('validated', 'Validated'), ('document_uploaded', 'Document uploaded'), ('document_reviewed', 'Document reviewed'), ('program_added', 'Program added'), ('program_suggested', 'Program suggested'), ('program_response', 'Program response'), ('recommendations_generated', 'Recommendations generated'), ('finalized', 'Finalized')], max_length=40),
        ),
    ]
