# Generated by Django 5.2.17 on 2026-08-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadprograminterest',
            name='converted_application',
        ),
    ]
