# Generated by Django 5.2.17 on 2026-09-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_leadprograminterest_converted_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('reopened', 'Reopened'), ('finalized', 'Finalized'), ('closed', 'Closed')], db_index=True, default='new', max_length=32),
        ),
    ]
