# Generated by Django 5.2.17 on 2026-08-27 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_leadactivity_activity_type'),
        ('messaging', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaddocument',
            name='source_message_attachment',
            field=models.OneToOneField(blank=True, help_text='Chat attachment this document was promoted from, when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_document', to='messaging.messageattachment'),
        ),
    ]
