# Generated by Django 5.2.17 on 2026-08-27 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_fa', models.CharField(blank=True, max_length=255)),
                ('name_tr', models.CharField(blank=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('slug_en', models.SlugField(max_length=255)),
                ('slug_fa', models.SlugField(blank=True, max_length=255)),
                ('slug_tr', models.SlugField(blank=True, max_length=255)),
                ('slug_ar', models.SlugField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('iso2', models.CharField(help_text='ISO 3166-1 alpha-2 country code, for example NL, TR, or IR.', max_length=2, unique=True)),
                ('iso3', models.CharField(help_text='ISO 3166-1 alpha-3 country code, for example NLD, TUR, or IRN.', max_length=3, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name_en',),
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_fa', models.CharField(blank=True, max_length=255)),
                ('name_tr', models.CharField(blank=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('slug_en', models.SlugField(max_length=255)),
                ('slug_fa', models.SlugField(blank=True, max_length=255)),
                ('slug_tr', models.SlugField(blank=True, max_length=255)),
                ('slug_ar', models.SlugField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provinces', to='geography.country')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_fa', models.CharField(blank=True, max_length=255)),
                ('name_tr', models.CharField(blank=True, max_length=255)),
                ('name_ar', models.CharField(blank=True, max_length=255)),
                ('slug_en', models.SlugField(max_length=255)),
                ('slug_fa', models.SlugField(blank=True, max_length=255)),
                ('slug_tr', models.SlugField(blank=True, max_length=255)),
                ('slug_ar', models.SlugField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='geography.province')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
