# Generated by Django 5.2.17 on 2026-08-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ("name_en",)},
        ),
    ]
