# Generated by Django 5.2.17 on 2026-08-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug_tr',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug_tr',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='province',
            name='slug_ar',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='province',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='province',
            name='slug_tr',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255),
        ),
    ]
