# Generated by Django 5.2.17 on 2026-08-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_alter_city_slug_ar_alter_city_slug_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='province',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
