# Generated by Django 5.2.17 on 2026-09-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_alter_city_slug_en_alter_country_slug_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='description_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='description_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_description_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_description_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_title_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_title_fa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='seo_title_tr',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
