# Generated by Django 5.2.17 on 2026-09-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_city_description_ar_city_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='banner',
            field=models.ImageField(blank=True, help_text='Main banner image used on the public City landing page.', upload_to='cities/banners/'),
        ),
        migrations.AddField(
            model_name='city',
            name='banner_alt_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='banner_alt_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='banner_alt_fa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='city',
            name='banner_alt_tr',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
