# Generated by Django 5.2.17 on 2026-08-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentdocument",
            options={"ordering": ("-created_at",)},
        ),
    ]
