# Generated by Django 5.2.17 on 2026-08-28 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField()),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('in_person', 'In person'), ('video_call', 'Video call'), ('other', 'Other')], max_length=20)),
                ('counterparty_type', models.CharField(choices=[('customer', 'Customer'), ('university', 'University'), ('other', 'Other')], max_length=20)),
                ('counterparty_name', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField()),
                ('subject_object_id', models.UUIDField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='agents.agent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_communication_logs', to=settings.AUTH_USER_MODEL)),
                ('subject_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_communication_logs', to='contenttypes.contenttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CommunicationLogRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='operations.communicationlog')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subject_object_id', models.UUIDField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='agents.agent')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agent_todos', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_todos', to='contenttypes.contenttype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', 'due_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='TodoComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operations.todo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['agent', 'occurred_at'], name='operations__agent_i_0af763_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationlog',
            index=models.Index(fields=['subject_content_type', 'subject_object_id'], name='operations__subject_56cd78_idx'),
        ),
        migrations.AddConstraint(
            model_name='communicationlog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('subject_content_type__isnull', True), ('subject_object_id__isnull', True)), models.Q(('subject_content_type__isnull', False), ('subject_object_id__isnull', False)), _connector='OR'), name='communication_subject_pair_consistent'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['agent', 'status', 'due_date'], name='operations__agent_i_1753ec_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['subject_content_type', 'subject_object_id'], name='operations__subject_86d0fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='todo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('subject_content_type__isnull', True), ('subject_object_id__isnull', True)), models.Q(('subject_content_type__isnull', False), ('subject_object_id__isnull', False)), _connector='OR'), name='todo_subject_pair_consistent'),
        ),
    ]
